  11. Create a Web content directory Create a playbook called
      /home/admin/ansible/webcontent.yml as follows:
    * The playbook runs managed node in the dev host group
    * Create the directory /webdev with the following requirement:
        - it is owner by the webdev group
      -it has regular permissions: owner=read+write+execute,group=r+w+x,other=r+x
        - it has special permission: set group GID
    * Symbolically link /webdev to /var/www/html/webdev
    * Create the file /web/index.html with a single line of text that reads: Development
    * Browsing this directory on host in the dev host group ( for example
      http://system1.domain1.example.com/webdev/) produces the following output:
    Development


    [admin@control ansible]$ vim webcontent.yml

      - hosts: dev
        tasks:
          - name: Add group
            group:
              name: webdev
              state: present

          - name: Create a directory
            ansible.builtin.file:
              name: /webdev
              group: webdev
              mode:  2775
              state: directory
              setype: httpd_sys_content_t

          - name: Create symbolic link
            ansible.builtin.file:
              src: /webdev
              dest: /var/www/html/webdev
              state: link

          - name: Create file in /var/www/html
            ansible.builtin.copy:
              content: development
              dest: /var/www/html/webdev/index.html



    :wq!

    [admin@control ansible]$ ansible-navigator run  webcontent.yml -m stdout
    [admin@control ansible]$ curl http://servera.lab.example.com/devweb/