  4. Ansible Content Collections.
    Location of Collection inside http://utility.lab13.example.com/materails
    1. install the redhat.rhel_system_roles-1.19.3.tar.gz collection
    2. install the posix-1.20.2.tar.gz collection
    3. install the community-general-5.5.0.tar.gz collection



  Answer-4:

    1) First at all, Open this link in new tab of exam browser http://utility.lab13.example.com/materails
    2) Then you can see that here 5 tar file avialable, In case you download question defined tar file like :-  redhat.rhel_system_roles-1.19.3.tar.gz collection , posix-1.20.2.tar.gz collection,
    community-general-5.5.0.tar.gz collection. right click on difined link and save link  location
    
    [admin@control ~]$ cd ~/ansible/mycollection
    [admin@control mycollection]$ wget http://utility.lab13.example.com/materails/redhat.rhel_system_roles-1.19.3.tar.gz
    [admin@control mycollection]$ wget http://utility.lab13.example.com/materails/posix-1.20.2.tar.gz
    [admin@control mycollection]$ wget http://utility.lab13.example.com/materails/community-general-5.5.0.tar.gz
    [admin@control mycollection]$ ansible-galaxy collection install redhat.rhel_system_roles-1.19.3.tar.gz -p collections
    [admin@control mycollection]$ ansible-galaxy collection install posix-1.20.2.tar.gz collection  -p collections
    [admin@control mycollection]$ ansible-galaxy collection installcommunity-general-5.5.0.tar.gz collection -p collections
    
    or
    [admin@control mycollection]$ ansible-galaxy collection install http://utility.lab13.example.com/materails/community-general-5.5.0.tar.gz -p collections
    [admin@control mycollection]$ ansible-galaxy collection install http://utility.lab13.example.com/materails/posix-1.20.2.tar.gz  -p collections
    [admin@control mycollection]$ ansible-galaxy collection install http://utility.lab13.example.com/materails/community-general-5.5.0.tar.gz -p collections
