  7. Create & use a role
      Create a role called apache in /home/admin/ansible/roles with the following requirement:
        - The httpd package is install, enabled on boot and started
        - The Firewall is enabled & running with a rule to allow access the web server
        - A template file index.html.j2 exists and is used to create the file /var/www/html/index.html
    with the Welcome to HOSTNAME ON IPADDRESS where HOSTNAME is the fqdn of the
    managed node and ip address is the ip address of managed node
    * create a playbook called /home/admin/ansible/newrole.yml that uses this role as follow: -
    The playbook runs on host in the webservers host group


    [admin@control ~]$ cd ansible/roles/
    
    [admin@control roles]$ ansible-galaxy init apache
    
    [admin@control roles]$ vim apache/tasks/main.yml

      - name: Install httpd package
        ansible.builtin.dnf:
          name:
            - httpd
            - firewalld
          state: present

      - name: start service httpd
        ansible.builtin.service:
          name: httpd
          state: started
          enabled: yes

      - name: start service firewalld
        ansible.builtin.service:
          name: firewalld
          state: started
          enabled: yes

      - name: Add http service in firewall rule
        ansible.posix.firewalld:
          service: http
          state: enabled
          permanent: yes
          immediate: yes

      - name: Copy the template.j2 file to web server directory
        ansible.builtin.template:
          src: template.j2
          dest: /var/www/html/index.html
    :wq!

    [admin@control roles]$ vim apache/templates/index.html.j2
    
    Welcome to {{ ansible_fqdn }} on {{ ansible_default_ipv4.address}}
    
    :wq!
    
    [admin@control roles]$ cd ../
    
    [admin@control ansible]$ vim newrole.yml

      - hosts: webservers
        roles:
          - apache

    :wq!


    [admin@control ansible]$ ansible-navigator run apache_role.yml -m stdout
    [admin@control ansible]$ curl http://servera.lab.example.com